/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin-files-manager': RouteRecordInfo<'admin-files-manager', '/admin/files/manager', Record<never, never>, Record<never, never>>,
    'admin-permissions': RouteRecordInfo<'admin-permissions', '/admin/permissions', Record<never, never>, Record<never, never>>,
    'apps-common-branch': RouteRecordInfo<'apps-common-branch', '/apps/common/branch', Record<never, never>, Record<never, never>>,
    'apps-common-language': RouteRecordInfo<'apps-common-language', '/apps/common/language', Record<never, never>, Record<never, never>>,
    'apps-content-id': RouteRecordInfo<'apps-content-id', '/apps/content/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-content-blog': RouteRecordInfo<'apps-content-blog', '/apps/content/blog', Record<never, never>, Record<never, never>>,
    'apps-content-builder': RouteRecordInfo<'apps-content-builder', '/apps/content/builder', Record<never, never>, Record<never, never>>,
    'apps-content-faq': RouteRecordInfo<'apps-content-faq', '/apps/content/faq', Record<never, never>, Record<never, never>>,
    'apps-content-gallery': RouteRecordInfo<'apps-content-gallery', '/apps/content/gallery', Record<never, never>, Record<never, never>>,
    'apps-content-inquiry': RouteRecordInfo<'apps-content-inquiry', '/apps/content/inquiry', Record<never, never>, Record<never, never>>,
    'apps-content-list': RouteRecordInfo<'apps-content-list', '/apps/content/list', Record<never, never>, Record<never, never>>,
    'apps-content-requirement': RouteRecordInfo<'apps-content-requirement', '/apps/content/requirement', Record<never, never>, Record<never, never>>,
    'apps-content-testimonial': RouteRecordInfo<'apps-content-testimonial', '/apps/content/testimonial', Record<never, never>, Record<never, never>>,
    'apps-course': RouteRecordInfo<'apps-course', '/apps/course', Record<never, never>, Record<never, never>>,
    'apps-course-category': RouteRecordInfo<'apps-course-category', '/apps/course/category', Record<never, never>, Record<never, never>>,
    'apps-course-democategory': RouteRecordInfo<'apps-course-democategory', '/apps/course/democategory', Record<never, never>, Record<never, never>>,
    'apps-course-tag': RouteRecordInfo<'apps-course-tag', '/apps/course/tag', Record<never, never>, Record<never, never>>,
    'apps-exam': RouteRecordInfo<'apps-exam', '/apps/exam', Record<never, never>, Record<never, never>>,
    'apps-learner': RouteRecordInfo<'apps-learner', '/apps/learner', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
  }
}
