fragment BlogFields on Blog {
  id
  title
  slug
  image
  thumbnail
  content
  author
  tags
  status
  createdBy
  updatedBy
  createdAt
  updatedAt
}
query AllBlog {
  AllBlog {
    ...BlogFields
  }
}

query AllActiveBlog {
  AllBlog(where: { status: { equals: ACTIVE } }) {
    ...BlogFields
  }
}

query Blog($id: ID!) {
  Blog(id: $id) {
    ...BlogFields
  }
}

mutation CreateBlog(
  $title: String!
  $image: String
  $thumbnail: String
  $content: String!
  $author: String
  $tags: String
) {
  CreateBlog(
    data: {
      title: $title
      image: $image
      thumbnail: $thumbnail
      content: $content
      author: $author
      tags: $tags
    }
  ) {
    ...BlogFields
  }
}

mutation UpdateBlog($id: ID!, $data: BlogUpdateInput!) {
  UpdateBlog(id: $id, data: $data) {
    ...BlogFields
  }
}

mutation UpdateBlogStatus($id: ID!, $status: Status!) {
  UpdateBlog(id: $id, data: { status: $status }) {
    id
    status
  }
}

mutation DeleteBlog($id: ID!) {
  DeleteBlog(id: $id)
}

mutation RepositionBlog($fromIndex: Int!, $toIndex: Int!) {
  RepositionBlog(data: { fromIndex: $fromIndex, toIndex: $toIndex })
}
