
fragment FaqFields on Faq {
  id
  question
  answer
  position
  status
  createdBy
  updatedBy
  createdAt
  updatedAt
}


query AllFaq {
  AllFaq {
    ...FaqFields
  }
}

query AllActiveFaq {
  AllFaq(where: { status: { equals: ACTIVE } }) {
    ...FaqFields
  }
}

query Faq($id: ID!) {
  Faq(id: $id) {
    ...FaqFields
  }
}


mutation CreateFaq(
  $question: String!
  $answer: String!
) {
  CreateFaq(
    data: {
      question: $question
      answer: $answer
    }
  ) {
    ...FaqFields
  }
}

mutation UpdateFaq($id: ID!, $data: FaqUpdateInput!) {
  UpdateFaq(id: $id, data: $data) {
    ...FaqFields
  }
}

mutation UpdateFaqStatus($id: ID!, $status: Status!) {
  UpdateFaq(id: $id, data: { status: $status }) {
    id
    status
  }
}

mutation DeleteFaq($id: ID!) {
  DeleteFaq(id: $id)
}

mutation RepositionFaq($fromIndex: Int!, $toIndex: Int!) {
  RepositionFaq(data: { fromIndex: $fromIndex, toIndex: $toIndex })
}
