fragment GalleryFields on Gallery {
  id
  image
  shortDescription
  position
  status
  createdBy
  updatedBy
  createdAt
  updatedAt
  galleryCategoryId
  GalleryCategory {
    name
  }
}

query AllGallery {
  AllGallery {
    ...GalleryFields
  }
}

query AllActiveGallery  {
  AllGallery(where: { status: { equals: ACTIVE } }) {
    ...GalleryFields
  }
}


query Gallery($id: ID!) {
  Gallery(id: $id) {
    ...GalleryFields
  }
}

mutation CreateGallery(
  $image: String!
  $shortDescription: String
  $status: Status
  $galleryCategoryId: String
) {
  CreateGallery(
    data: {
      image: $image
      shortDescription: $shortDescription
      status: $status
      GalleryCategory: { connect: { id: $galleryCategoryId } }

    }
  ) {
    ...GalleryFields
  }
}



mutation UpdateGallery(
  $id: ID!
  $image: String
  $shortDescription: String
  $status: Status
  $galleryCategoryId: String
) {
  UpdateGallery(
    id: $id
    data: {
      image: $image
      shortDescription: $shortDescription
      status: $status
      GalleryCategory: { connect: { id: $galleryCategoryId } }
    }
  ) {
    ...GalleryFields
  }
}

mutation UpdateGalleryStatus($id: ID!, $status: Status!) {
  UpdateGallery(id: $id, data: { status: $status }) {
    id
    status
  }
}

mutation DeleteGallery($id: ID!) {
  DeleteGallery(id: $id)
}

mutation RepositionGallery($fromIndex: Int!, $toIndex: Int!) {
  RepositionGallery(data: { fromIndex: $fromIndex, toIndex: $toIndex })
}
