fragment GalleryCategoryFields on GalleryCategory {
  id
  name
  position
  status
  createdBy
  updatedBy
  createdAt
  updatedAt
}

query AllGalleryCategory {
  AllGalleryCategory(
    orderBy: [ {
       position: asc
    }]
  ) {
    ...GalleryCategoryFields
  }
}

query AllActiveGalleryCategory  {
  AllGalleryCategory(where: { status: { equals: ACTIVE } }) {
    ...GalleryCategoryFields
  }
}


query GalleryCategory($id: ID!) {
  GalleryCategory(id: $id) {
    ...GalleryCategoryFields
  }
}

mutation CreateGalleryCategory(
  $name: String!
) {
  CreateGalleryCategory(
    data: {
      name: $name

    }
  ) {
    ...GalleryCategoryFields
  }
}



mutation UpdateGalleryCategory(
  $id: ID!
  $name: String
) {
  UpdateGalleryCategory(
    id: $id
    data: {
      name: $name
    }
  ) {
    ...GalleryCategoryFields
  }
}

mutation UpdateGalleryCategoryStatus($id: ID!, $status: Status!) {
  UpdateGalleryCategory(id: $id, data: { status: $status }) {
    id
    status
  }
}

mutation DeleteGalleryCategory($id: ID!) {
  DeleteGalleryCategory(id: $id)
}

mutation RepositionGalleryCategory($fromIndex: Int!, $toIndex: Int!) {
  RepositionGalleryCategory(data: { fromIndex: $fromIndex, toIndex: $toIndex })
}
