fragment TestimonialFields on Testimonial {
  id
  name
  designation
  message
  image
  position
  status
  createdBy
  updatedBy
  createdAt
  updatedAt
}
query AllTestimonial {
  AllTestimonial {
    ...TestimonialFields
  }
}

query AllActiveTestimonial {
  AllTestimonial(where: { status: { equals: ACTIVE } }) {
    ...TestimonialFields
  }
}

query Testimonial($id: ID!) {
  Testimonial(id: $id) {
    ...TestimonialFields
  }
}

mutation CreateTestimonial(
  $name: String!
  $designation: String
  $message: String!
  $image: String
) {
  CreateTestimonial(
    data: {
      name: $name
      designation: $designation
      message: $message
      image: $image
    }
  ) {
    ...TestimonialFields
  }
}

mutation UpdateTestimonial($id: ID!, $data: TestimonialUpdateInput!) {
  UpdateTestimonial(id: $id, data: $data) {
    ...TestimonialFields
  }
}

mutation UpdateTestimonialStatus($id: ID!, $status: Status!) {
  UpdateTestimonial(id: $id, data: { status: $status }) {
    id
    status
  }
}

mutation DeleteTestimonial($id: ID!) {
  DeleteTestimonial(id: $id)
}

mutation RepositionTestimonial($fromIndex: Int!, $toIndex: Int!) {
  RepositionTestimonial(data: { fromIndex: $fromIndex, toIndex: $toIndex })
}
