fragment CourseCategoryFields on CourseCategory {
  id
  name
  status
  position
  createdBy
  updatedBy
  createdAt
  updatedAt
}

query AllCourseCategory {
  AllCourseCategory {
    ...CourseCategoryFields
  }
}
query AllActiveCourseCategory  {
  AllCourseCategory(where: { status: { equals: ACTIVE } }) {
    ...CourseCategoryFields
  }
}

query CourseCategory($id: ID!) {
  CourseCategory(id: $id) {
    ...CourseCategoryFields
  }
}

mutation CreateCourseCategory($name: String!) {
  CreateCourseCategory(data: { name: $name }) {
    ...CourseCategoryFields
  }
}

mutation UpdateCourseCategory($id: ID!, $data: CourseCategoryUpdateInput!) {
  UpdateCourseCategory(id: $id, data: $data) {
    ...CourseCategoryFields
  }
}

mutation DeleteCourseCategory($id: ID!) {
  DeleteCourseCategory(id: $id)
}

mutation RepositionCourseCategory($fromIndex: Int!, $toIndex: Int!) {
  RepositionCourseCategory(data: { fromIndex: $fromIndex, toIndex: $toIndex })
}
