fragment LearnerCourseFields on LearnerCourse {
  id
  userId
  courseId
  progress
  status
  type
  currentExam
  enrolledAt
  completedAt
  expiryAt
  course {
    id
    name
    shortDescription
    description
    longDescription
    thumbnail
    videoUrl
    gallery
    isFree
    price
    documents
    isDiscounted
    finalPrice
    position
    status
    createdBy
    updatedBy
    createdAt
    updatedAt
    courseCategoryId
  }
}

query AllLearnerCourse {
  AllLearnerCourse {
    ...LearnerCourseFields
  }
}

query LearnerCourse($id: ID!) {
  LearnerCourse(id: $id) {
    ...LearnerCourseFields
  }
}

mutation CreateLearnerCourse(
  $userId: String!
  $courseId: String!
  $status: LearnerCourseStatus!
  $type: LearnerCourseType!
  $expiryAt: DateTime
) {
  CreateLearnerCourse(
    data: {
      user: { connect: { id: $userId } }
      course: { connect: { id: $courseId } }
      status: $status
      type: $type
      expiryAt: $expiryAt
    }
  ) {
    id
    userId
    courseId
    progress
    status
    type
    currentExam
    enrolledAt
    completedAt
    expiryAt
  }
}

mutation DeleteLearnerCourse($id: ID!) {
  DeleteLearnerCourse(id: $id)
}

mutation RepositionLearnerCourse($fromIndex: Int!, $toIndex: Int!) {
  RepositionLearnerCourse(data: { fromIndex: $fromIndex, toIndex: $toIndex })
}
