fragment TagFields on Tag {
  id
  name
  description
  status
  position
  createdBy
  updatedBy
  createdAt
  updatedAt
  }

query AllTag {
  AllTag(orderBy: [{ position: asc }]) {
    ...TagFields
  }
}

query Tag($id: ID!) {
  Tag(id: $id) {
    ...TagFields
  }
}

mutation CreateTag($name: String!, $description: String) {
  CreateTag(data: { name: $name, description: $description }) {
    ...TagFields
  }
}

mutation UpdateTag($id: ID!, $data: TagUpdateInput!) {
  UpdateTag(id: $id, data: $data) {
    ...TagFields
  }
}

mutation DeleteTag($id: ID!) {
  DeleteTag(id: $id)
}

mutation RepositionTag($fromIndex: Int!, $toIndex: Int!) {
  RepositionTag(data: { fromIndex: $fromIndex, toIndex: $toIndex })
}
