fragment LanguageFields on Language {
  id
  name
  description
  code
  icon
  status
  position
  createdBy
  updatedBy
  createdAt
  updatedAt
}

query AllLanguage {
  AllLanguage {
    ...LanguageFields
  }
}
query AllActiveLanguage {
  AllLanguage(where: { status: { equals: ACTIVE } }) {
    ...LanguageFields
  }
}

query Language($id: ID!) {
  Language(id: $id) {
    ...LanguageFields
  }
}

mutation CreateLanguage(
  $name: String!
  $description: String
  $code: String!
  $icon: String!
) {
  CreateLanguage(
    data: { name: $name, description: $description, code: $code, icon: $icon }
  ) {
    ...LanguageFields
  }
}

mutation UpdateLanguage($id: ID!, $data: LanguageUpdateInput!) {
  UpdateLanguage(id: $id, data: $data) {
    ...LanguageFields
  }
}

mutation DeleteLanguage($id: ID!) {
  DeleteLanguage(id: $id)
}

mutation RepositionLanguage($fromIndex: Int!, $toIndex: Int!) {
  RepositionLanguage(data: { fromIndex: $fromIndex, toIndex: $toIndex })
}
